language: node_js
node_js:
- 10
deploy:
  provider: npm
  email: betterofsong@gmail.com
api_key:
  secure: DheP2od7sLhZA8993rapiSGCgf+/lS63ge/TboJ6Cms/71PNdvwe0co6eslhgzJuKucT5170T913lgn+tKN3tbrZ65UiibP7l5vYoX9rSTUtDDD5HryqwqwlXO2EBHDflaNmHNVSnIdXX8h3Vj4x/ThQEN4sT8f8PEYbG1An7e7ERG3lKM3jMOUHpUGJxkK8/v6fzCtPiXSD4OTwUdSASik4IqqugWd6LLn2kj0QzK1u60urMTRnz2PP1h4I7NOvMmVLxrOWDRLEOu6MK9F7AJftOEjSqRK8EE+rg04HM6+UVKnYulfqlPZtV7ujpu5LVEC9ATX8cNAjCy6px44OK3o4s5KtIH8gpZY/n6qb+XESnmgKs5lqSAj0oIU5gHw/SK86asbm4f+HV7PM/UtrloXpKUh0UCVDh8mJc0JayxCUqlFGdR3S0CgcqKcYOMrsNkund8kuHd9HVuHJR0jPfqL7Jz8y+Ss5mm6LMc6XLzZxzjoi0L8hMPL//DLBumgUCyfpMZWU0/E1VWa3UkvqxeO3pFgL0n1jGOw/RGY3VuB5XYPvBzP28QRZusZyvQAB9tfFt5WQW8+OI4qRywR8vLTXctpI0rWnPoK6smzxoxpiTPYN+NZT+lICVWUzIxI/HSIlW+TBAZIVLLBr9Wc4SqgMrOXIFIBuLk6ekM8lk/s=
