language: node_js
node_js:
- 10
deploy:
  provider: npm
  email: betterofsong@gmail.com
  api_key:
    secure: aSzNGrl8XPiR2CM07E7Gy7+DhH6dL8l9UM7bKR4soPZzCna55Oi5IaZCMQ2gTBribLr/Rhoj1ciONMnMVE1vD6P5VO462VXpaTf68j8fVY2XwjN7gWhQJVt+HGToPx/+YpEKQgYfu/rz30YdRFuvCMugLIsR1uf5EOYdhsP+nB6ZsnQ3FEwpGnysupVVx9mL5O2Kjd0NyBdAdk6UvDPidCOALEudPzYacUQ8zq/62kC2wRDtUm7K14WgabtsasvJOqLDr7d5x3+1NDUXVMJzBnLaSCA5vU0MQgaDKPbgBEJtc5nxnkQrfdaKUHMd590n0rXaGVuFPn9kU8zDw9A0QID2jyK0rSKeV3UZlDM/rIHtkmDlv8dGhg73uFfGNMfbynGz8wCwU70OPfgOo82Wj4KCKiF4V2yrWuzVG9sgwvpeXlgeFBsaN1+QDHvRW6vANUmhSKac4Z5I6OCVvRjWQullEOOWjZtTnq/GJfOOOn/PhOZgwlVWPQDbSl5HoreI67FU0U6ziua005d3l55tIADCWMld/7toeowvEajXLakGIodvg9dA/oewVfzlR8omKPjpK4vJK0onWIx/L+1E2qFN88ee7bHc3dr3xdRXFgCjH+SAVHFkwq6YC6xQe3lcC/eZaQ1dXspyRMSw22MQnGUPArgmi1Z/5cYH9QUisWk=
